// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "SWAPI Lambda API (POST)",
    "version": "1"
  },
  "paths": {
    "/api/favorites": {
      "post": {
        "summary": "Create Favorite",
        "description": "Crear un nuevo personaje favorito",
        "operationId": "createFavorite.post./api/favorites",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/api/favorites/{id}": {
      "delete": {
        "summary": "Delete Favorite",
        "description": "Eliminar personaje favorito por ID",
        "operationId": "deleteFavorite.delete./api/favorites/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/api/migrate": {
      "get": {
        "summary": "Migrate DB",
        "description": "Ejecutar script de migración SQL para la tabla de favoritos",
        "operationId": "migrateFavorites.get./api/migrate",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    }
  },
  "definitions": {},
  "securityDefinitions": {},
  "basePath": "/",
  "host": "lvryteny8c.execute-api.us-east-1.amazonaws.com"
};